[Interface]
PrivateKey = CKNmZlg4TDBGqayef0aKPdBxaoxUr98OwhtLJMf23kE=
Address = 10.0.0.2/24

[Peer]
PublicKey = 
Endpoint = 185.13.180.223:51820
AllowedIPs = 0.0.0.0/0, ::/0 # Permet de router tout le trafic
PersistentKeepalive = 25
