[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = mEwSA6sIJwzUWNshyhz7M/N4DOZJsm96d4kxVSBVsX0=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = UNVyJfgl74Eapd11ojAhXf4nmxvXh3Z2+xN3yfFtilE= | wg pubkey
AllowedIPs = 10.0.0.2/32

