[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = iKKn7cWFX90HuYABW2T0zvyxU6c5aN+GsC9OiRqwME8=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = mF1xHq4pGbVK+utFx8WbMnthNpg24w5pUWxudQ0vvFY= | wg pubkey
AllowedIPs = 10.0.0.2/32

