[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = OBNBLhBunsg5xy0D2JCId7ulPeB99K29ekG5dilArWA=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = EwQFM6v57at7b+jaAuB83P3+btOTEcpJ4xyRA56cFHI=
AllowedIPs = 10.0.0.2/32
